# -*- coding: utf-8 -*-
"""student info.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CNvztXLbEsVs1-dwuwPuQuggnCM1j55B
"""

pip install faker

import pandas as pd
import numpy as np
from faker import Faker

fake = Faker()

num_students = 250

student_ids = [f'S{i:03d}' for i in range(1, num_students + 1)]
names = [fake.name() for _ in range(num_students)]
genders = np.random.choice(['Male', 'Female'], num_students)
departments = np.random.choice(['CSE', 'IT', 'ECE'], num_students)
years = np.random.choice(['1st', '2nd', '3rd'], num_students)
maths_marks = np.random.randint(40, 100, num_students)
science_marks = np.random.randint(40, 100, num_students)
english_marks = np.random.randint(40, 100, num_students)
attendance = np.random.randint(50, 101, num_students)
internal_marks = np.random.randint(0, 26, num_students)

students_data = pd.DataFrame({
    'Student_ID': student_ids,
    'Name': names,
    'Gender': genders,
    'Department': departments,
    'Year': years,
    'Maths': maths_marks,
    'Science': science_marks,
    'English': english_marks,
    'Attendance (%)': attendance,
    'Internal Marks': internal_marks
})

display(students_data)

students_data.info()

students_data.isnull().sum()

import matplotlib.pyplot as plt

# 1. Calculate and display descriptive statistics for numerical columns
numerical_columns = ['Maths', 'Science', 'English', 'Attendance (%)', 'Internal Marks']
descriptive_stats = students_data[numerical_columns].describe()
print("Descriptive Statistics for Numerical Columns:")
print(descriptive_stats)

# 2. Generate and display histograms for 'Maths', 'Science', and 'English'
plt.figure(figsize=(18, 6))

plt.subplot(1, 3, 1)
plt.hist(students_data['Maths'], bins=10, edgecolor='black', color='skyblue')
plt.xlabel('Marks')
plt.ylabel('Frequency')
plt.title('Distribution of Maths Marks')

plt.subplot(1, 3, 2)
plt.hist(students_data['Science'], bins=10, edgecolor='black', color='lightcoral')
plt.xlabel('Marks')
plt.ylabel('Frequency')
plt.title('Distribution of Science Marks')

plt.subplot(1, 3, 3)
plt.hist(students_data['English'], bins=10, edgecolor='black', color='lightgreen')
plt.xlabel('Marks')
plt.ylabel('Frequency')
plt.title('Distribution of English Marks')

plt.tight_layout()
plt.show()

import pandas as pd

# 1. Calculate 'Total Marks'
students_data['Total Marks'] = students_data['Maths'] + students_data['Science'] + students_data['English']

# 2. Calculate 'Average Marks'
students_data['Average Marks'] = students_data['Total Marks'] / 3

# 3. Define the grading system function
def get_grade(average_marks):
    if average_marks >= 90:
        return 'A'
    elif average_marks >= 80:
        return 'B'
    elif average_marks >= 70:
        return 'C'
    elif average_marks >= 60:
        return 'D'
    else:
        return 'F'

# 4. Apply the grading system to create the 'Grade' column
students_data['Grade'] = students_data['Average Marks'].apply(get_grade)

# 5. Display the first few rows of the updated DataFrame
display(students_data.head())

print("Top 10 Performing Students (based on Total Marks):")
top_10_students = students_data.sort_values(by='Total Marks', ascending=False).head(10)
display(top_10_students)

print("\nStudents with 'F' Grade (Low Performers):")
low_performing_students = students_data[students_data['Grade'] == 'F']
display(low_performing_students)

import matplotlib.pyplot as plt

# 1. Calculate average 'Total Marks' by 'Department'
department_performance = students_data.groupby('Department')['Total Marks'].mean()
print("\nAverage Total Marks by Department:")
print(department_performance)

# 2. Calculate average 'Total Marks' by 'Gender'
gender_performance = students_data.groupby('Gender')['Total Marks'].mean()
print("\nAverage Total Marks by Gender:")
print(gender_performance)

# 3. Calculate average 'Total Marks' by 'Year'
year_performance = students_data.groupby('Year')['Total Marks'].mean()
print("\nAverage Total Marks by Year:")
print(year_performance)

# Visualize the analyses using bar charts
plt.figure(figsize=(18, 6))

# Bar chart for Department-wise performance
plt.subplot(1, 3, 1)
department_performance.plot(kind='bar', color='skyblue')
plt.xlabel('Department')
plt.ylabel('Average Total Marks')
plt.title('Average Total Marks by Department')
plt.xticks(rotation=45, ha='right')

# Bar chart for Gender-wise performance
plt.subplot(1, 3, 2)
gender_performance.plot(kind='bar', color=['lightcoral', 'lightgreen'])
plt.xlabel('Gender')
plt.ylabel('Average Total Marks')
plt.title('Average Total Marks by Gender')
plt.xticks(rotation=45, ha='right')

# Bar chart for Year-wise performance
plt.subplot(1, 3, 3)
year_performance.plot(kind='bar', color='gold')
plt.xlabel('Year')
plt.ylabel('Average Total Marks')
plt.title('Average Total Marks by Year')
plt.xticks(rotation=45, ha='right')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

# Create a figure with two subplots
plt.figure(figsize=(15, 6))

# Scatter plot for 'Attendance (%)' vs 'Total Marks'
plt.subplot(1, 2, 1)
plt.scatter(students_data['Attendance (%)'], students_data['Total Marks'], color='blue', alpha=0.7, label='Students')
plt.xlabel('Attendance (%)')
plt.ylabel('Total Marks')
plt.title('Attendance (%) vs. Total Marks')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)

# Scatter plot for 'Internal Marks' vs 'Total Marks'
plt.subplot(1, 2, 2)
plt.scatter(students_data['Internal Marks'], students_data['Total Marks'], color='red', alpha=0.7, label='Students')
plt.xlabel('Internal Marks')
plt.ylabel('Total Marks')
plt.title('Internal Marks vs. Total Marks')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout()
plt.show()

# Calculate and print correlation coefficients
correlation_attendance_total = students_data['Attendance (%)'].corr(students_data['Total Marks'])
print(f"\nPearson Correlation between Attendance (%) and Total Marks: {correlation_attendance_total:.2f}")

correlation_internal_total = students_data['Internal Marks'].corr(students_data['Total Marks'])
print(f"Pearson Correlation between Internal Marks and Total Marks: {correlation_internal_total:.2f}")

import matplotlib.pyplot as plt

# 1. Create a figure to display multiple plots
plt.figure(figsize=(20, 8))

# 2. Histogram for 'Total Marks'
plt.subplot(1, 3, 1) # 1 row, 3 columns, first plot
plt.hist(students_data['Total Marks'], bins=15, edgecolor='black', color='skyblue')
plt.xlabel('Total Marks')
plt.ylabel('Frequency')
plt.title('Distribution of Total Marks')

# 3. Histogram for 'Average Marks'
plt.subplot(1, 3, 2) # 1 row, 3 columns, second plot
plt.hist(students_data['Average Marks'], bins=15, edgecolor='black', color='lightcoral')
plt.xlabel('Average Marks')
plt.ylabel('Frequency')
plt.title('Distribution of Average Marks')

# 4. Calculate the counts of students for each unique 'Grade' category
grade_counts = students_data['Grade'].value_counts()

# 5. Create a pie chart for 'Grade' distribution
plt.subplot(1, 3, 3) # 1 row, 3 columns, third plot
plt.pie(grade_counts, labels=grade_counts.index, autopct='%1.1f%%', startangle=90, colors=plt.cm.Paired.colors, wedgeprops={'edgecolor': 'black'})
plt.title('Proportion of Students by Grade')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.

# 6. Display all generated plots
plt.tight_layout()
plt.show()